<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>

<?php $url = "http://localhost/Cybercom/php/24-02-2020/Public/"; ?>

<div>
    <nav>
        <li><a href="<?php echo $url.""; ?>">Home</a></li>
        <li><a href="<?php echo $url."Home/addUser"; ?>">Add User</a></li>
    </nav>
</div>
    