<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>

<style>
    li{
        margin-left: 20px;
    }
    nav{
        display: inline-flex;
    }
    table, th, td {
        border: 1px solid black;
        padding: 5px;
    }
</style>
<body>
<?php $url = "http://localhost/Cybercom/php/24-02-2020/MVC/Public/"; ?>

<div>
    <nav>
        <li><a href="<?php echo $url.""; ?>">Home</a></li>
        <li><a href="<?php echo $url."Home/addUser"; ?>">Add User</a></li>
    </nav>
</div>
    